/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sections?: Array<
    | ({
        _key: string;
      } & HeroBlock)
    | ({
        _key: string;
      } & EventsBlock)
    | ({
        _key: string;
      } & OnTapBlock)
    | ({
        _key: string;
      } & OfferingsBlock)
    | ({
        _key: string;
      } & GalleryBlock)
    | ({
        _key: string;
      } & AboutBlock)
    | ({
        _key: string;
      } & FeatureBlock)
    | ({
        _key: string;
      } & DividerBlock)
  >;
};

export type DividerBlock = {
  _type: "dividerBlock";
  hiddenOnSite?: boolean;
  menuLabel?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type FeatureBlock = {
  _type: "featureBlock";
  eyebrow?: string;
  heading: string;
  body?: string;
  photos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  photoSide?: "right" | "left";
  listHeading?: string;
  listItems?: Array<string>;
  listAsOf?: string;
  ctaLabel?: string;
  ctaUrl?: string;
  hiddenOnSite?: boolean;
  menuLabel?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type AboutBlock = {
  _type: "aboutBlock";
  heading?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  credentials?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  hiddenOnSite?: boolean;
  menuLabel?: string;
};

export type GalleryBlock = {
  _type: "galleryBlock";
  heading?: string;
  photos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  hiddenOnSite?: boolean;
  menuLabel?: string;
};

export type OfferingsBlock = {
  _type: "offeringsBlock";
  heading?: string;
  cards?: Array<{
    title: string;
    description: string;
    _type: "offering";
    _key: string;
  }>;
  hiddenOnSite?: boolean;
  menuLabel?: string;
};

export type OnTapBlock = {
  _type: "onTapBlock";
  heading?: string;
  blurb?: string;
  secondary?: string;
  secondaryLinkLabel?: string;
  cta?: string;
  tapCount?: number;
  tapCountLabel?: string;
  tapCountFootnote?: string;
  perks?: Array<string>;
  hiddenOnSite?: boolean;
  menuLabel?: string;
};

export type EventsBlock = {
  _type: "eventsBlock";
  heading?: string;
  weeklyHeading?: string;
  hiddenOnSite?: boolean;
  menuLabel?: string;
};

export type HeroBlock = {
  _type: "heroBlock";
  heading: string;
  subheading?: string;
  primaryCta?: string;
  secondaryCta?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  hiddenOnSite?: boolean;
  menuLabel?: string;
};

export type PipelineState = {
  _id: string;
  _type: "pipelineState";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  cursor?: string;
  processedPostIds?: Array<string>;
};

export type WeeklyEvent = {
  _id: string;
  _type: "weeklyEvent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  dayOfWeek:
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday"
    | "Sunday";
  time: string;
  category: "music" | "art" | "games" | "party" | "community";
  description?: string;
  active?: boolean;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  start: string;
  endTime?: string;
  category: "music" | "art" | "games" | "party" | "community";
  description?: string;
  link?: string;
  source?: {
    fbPostId?: string;
    ingestedAt?: string;
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  announcement?: string;
  name: string;
  tagline?: string;
  addressLine1: string;
  addressLine2: string;
  phone?: string;
  email?: string;
  untappdUrl: string;
  instagramUrl?: string;
  facebookUrl?: string;
  pipelineEmails?: Array<string>;
  hours?: Array<{
    day:
      | "Monday"
      | "Tuesday"
      | "Wednesday"
      | "Thursday"
      | "Friday"
      | "Saturday"
      | "Sunday";
    closed?: boolean;
    opens?: string;
    closes?: string;
    _type: "dayHours";
    _key: string;
  }>;
  footerHeading?: string;
  footerHoursLabel?: string;
  footerFindUsLabel?: string;
  footerFollowLabel?: string;
  footerDirectionsCta?: string;
  footerVisitLine?: string;
  footerLegal?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | HomePage
  | DividerBlock
  | SanityImageAssetReference
  | FeatureBlock
  | SanityImageCrop
  | SanityImageHotspot
  | AboutBlock
  | GalleryBlock
  | OfferingsBlock
  | OnTapBlock
  | EventsBlock
  | HeroBlock
  | PipelineState
  | WeeklyEvent
  | Event
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

// Source: src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    name, tagline, addressLine1, addressLine2, phone, email,    untappdUrl, instagramUrl, facebookUrl, announcement,    hours[]{_key, day, opens, closes, closed},    footerHeading, footerHoursLabel, footerFindUsLabel, footerFollowLabel,    footerDirectionsCta, footerVisitLine, footerLegal  }
export type SITE_SETTINGS_QUERY_RESULT = {
  name: string;
  tagline: string | null;
  addressLine1: string;
  addressLine2: string;
  phone: string | null;
  email: string | null;
  untappdUrl: string;
  instagramUrl: string | null;
  facebookUrl: string | null;
  announcement: string | null;
  hours: Array<{
    _key: string;
    day:
      | "Friday"
      | "Monday"
      | "Saturday"
      | "Sunday"
      | "Thursday"
      | "Tuesday"
      | "Wednesday";
    opens: string | null;
    closes: string | null;
    closed: boolean | null;
  }> | null;
  footerHeading: string | null;
  footerHoursLabel: string | null;
  footerFindUsLabel: string | null;
  footerFollowLabel: string | null;
  footerDirectionsCta: string | null;
  footerVisitLine: string | null;
  footerLegal: string | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event" && start >= $from] | order(start asc){    _id, title, start, endTime, category, description, link  }
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  start: string;
  endTime: string | null;
  category: "art" | "community" | "games" | "music" | "party";
  description: string | null;
  link: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: WEEKLY_EVENTS_QUERY
// Query: *[_type == "weeklyEvent" && active != false]{    _id, title, dayOfWeek, time, category, description  }
export type WEEKLY_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  dayOfWeek:
    | "Friday"
    | "Monday"
    | "Saturday"
    | "Sunday"
    | "Thursday"
    | "Tuesday"
    | "Wednesday";
  time: string;
  category: "art" | "community" | "games" | "music" | "party";
  description: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{ sections[]{ ... } }
export type HOME_PAGE_QUERY_RESULT = {
  sections: Array<
    | {
        _key: string;
        _type: "aboutBlock";
        heading?: string;
        body?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        credentials?: Array<string>;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        hiddenOnSite?: boolean;
        menuLabel?: string;
      }
    | {
        _key: string;
        _type: "dividerBlock";
        hiddenOnSite?: boolean;
        menuLabel?: string;
      }
    | {
        _key: string;
        _type: "eventsBlock";
        heading?: string;
        weeklyHeading?: string;
        hiddenOnSite?: boolean;
        menuLabel?: string;
      }
    | {
        _key: string;
        _type: "featureBlock";
        eyebrow?: string;
        heading: string;
        body?: string;
        photos?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          _type: "image";
          _key: string;
        }>;
        photoSide?: "left" | "right";
        listHeading?: string;
        listItems?: Array<string>;
        listAsOf?: string;
        ctaLabel?: string;
        ctaUrl?: string;
        hiddenOnSite?: boolean;
        menuLabel?: string;
      }
    | {
        _key: string;
        _type: "galleryBlock";
        heading?: string;
        photos?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt: string;
          caption?: string;
          _type: "image";
          _key: string;
        }>;
        hiddenOnSite?: boolean;
        menuLabel?: string;
      }
    | {
        _key: string;
        _type: "heroBlock";
        heading: string;
        subheading?: string;
        primaryCta?: string;
        secondaryCta?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        hiddenOnSite?: boolean;
        menuLabel?: string;
      }
    | {
        _key: string;
        _type: "offeringsBlock";
        heading?: string;
        cards?: Array<{
          title: string;
          description: string;
          _type: "offering";
          _key: string;
        }>;
        hiddenOnSite?: boolean;
        menuLabel?: string;
      }
    | {
        _key: string;
        _type: "onTapBlock";
        heading?: string;
        blurb?: string;
        secondary?: string;
        secondaryLinkLabel?: string;
        cta?: string;
        tapCount?: number;
        tapCountLabel?: string;
        tapCountFootnote?: string;
        perks?: Array<string>;
        hiddenOnSite?: boolean;
        menuLabel?: string;
      }
  > | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n    name, tagline, addressLine1, addressLine2, phone, email,\n    untappdUrl, instagramUrl, facebookUrl, announcement,\n    hours[]{_key, day, opens, closes, closed},\n    footerHeading, footerHoursLabel, footerFindUsLabel, footerFollowLabel,\n    footerDirectionsCta, footerVisitLine, footerLegal\n  }': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "event" && start >= $from] | order(start asc){\n    _id, title, start, endTime, category, description, link\n  }': EVENTS_QUERY_RESULT;
    '*[_type == "weeklyEvent" && active != false]{\n    _id, title, dayOfWeek, time, category, description\n  }': WEEKLY_EVENTS_QUERY_RESULT;
    '*[_type == "homePage"][0]{ sections[]{ ... } }': HOME_PAGE_QUERY_RESULT;
  }
}
